
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[constraint]]
  name = "github.com/katzenpost/authority"
  version = "0.0.3"

[[constraint]]
  branch = "reply_bookkeeping.0"
  name = "github.com/katzenpost/client"

[[constraint]]
  name = "github.com/katzenpost/core"
  version = "0.0.3"

[[constraint]]
  name = "github.com/katzenpost/mailproxy"
  version = "0.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/katzenpost/panda"

[[constraint]]
  name = "github.com/katzenpost/playground"
  version = "0.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/katzenpost/registration_client"

[[constraint]]
  name = "github.com/katzenpost/server"
  version = "0.0.3"


# other stuff

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/abiosoft/ishell"
  version = "2.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/hpcloud/tail"


[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true
