---
- name: rotate mix identity public key
  copy: src="{{ idPubKey }}" dest=/var/lib/katzenpost/identity.public.pem owner=katzenpost group=katzenpost mode=0600
  notify:
    - restart katzen-mix

- name: rotate mix identity private key
  copy: src="{{ idPrivKey }}" dest=/var/lib/katzenpost/identity.private.pem owner=katzenpost group=katzenpost mode=0600
  notify:
    - restart katzen-mix
