- name: install katzen-provider systemd unit file
  template: src=katzen-provider.j2 dest=/etc/systemd/system/katzen-provider.service
  notify:
    - reload systemd
    - restart katzen-provider

- name: install katzenmix-tailon systemd unit file
  template: src=katzenmix-tailon.j2 dest=/etc/systemd/system/katzenmix-tailon.service
  notify:
    - reload systemd
    - restart katzenmix-tailon
