- name: create /etc/katzenpost
  file:
    path: /etc/katzenpost
    state: directory

- name: update katzen-provider config
  copy: src="{{ providerConfig }}" dest=/etc/katzenpost/katzenpost.toml owner=root group=root mode=0644
  notify:
    - restart katzen-provider
