---
- name: update provider identity public key
  copy: src="{{ idPubKey }}" dest=/var/lib/katzenpost/identity.public.pem owner=katzenpost group=katzenpost mode=0600
  notify:
    - restart katzen-provider

- name: update provider identity private key
  copy: src="{{ idPrivKey }}" dest=/var/lib/katzenpost/identity.private.pem owner=katzenpost group=katzenpost mode=0600
  notify:
    - restart katzen-provider

- name: rotate provider link private key
  copy: src="{{ linkPrivKey }}" dest=/var/lib/katzenpost/link.private.pem owner=katzenpost group=katzenpost mode=0600
  notify:
    - restart katzen-provider
