- name: update provider identity key
  copy: src="{{ idPubKey }}" dest=/etc/katzenpost/identity.public.pem owner=root group=katzenpost mode=0640
  copy: src="{{ idPrivKey }}" dest=/etc/katzenpost/identity.private.pem owner=root group=katzenpost mode=0640
  notify:
    - restart katzen-provider
