# handler to handle mix notifications
- name: reload systemd
  systemd: state=started name=katzen-mix daemon_reload=yes enabled=yes

- name: start katzen-mix
  service: name=katzen-mix state=started enabled=yes

- name: restart katzen-mix
  service: name=katzen-mix state=restarted enabled=yes

- name: restart katzenmix-tailon
  service: name=katzenmix-tailon state=restarted enabled=yes
