
[Proxy]
  DataDir = "/home/user/.katzenpost"

[UpstreamProxy]
  Type = "none"

[Logging]
  Disable = false
  Level = "DEBUG"

[NonvotingAuthority]
  Address = "45.32.131.140:12483"
  PublicKey = "YbkiuJk+BkJFKJIX5NRnxkrWm9+32u/wE+3jkzieBHc="

[Account]
  User = "anonymous"
  Provider = "provider2"
  ProviderKeyPin = "akHTTDZ4setpOb3QzM1zN6+wMnMhA0VWQnWVooCKcxM="

[Debug]
  CaseSensitiveUserIdentifiers = false
  GenerateOnly = false
  PollingInterval = 10
