---
# XXX: clean this up.
- name: create build output directory
  file:
    path: "{{ buildDir }}"
    state: directory

- name: create temporary gopath
  file:
    path: "{{ buildDir }}/go"
    state: directory

    # if godep is not already present in path
- name: install godep
  environment:
    GOPATH: "{{ buildDir }}/go"
    PATH: "{{ buildDir }}/go/bin:{{ ansible_env.PATH }}"
  command: go get -u github.com/golang/dep/cmd/dep

- include: build_daemons.yml
- include: build_mailproxy.yml
