---
# XXX: clean this up.
- name: create build output directory
  file:
    path: "{{ buildDir }}"
    state: directory

- name: create temporary gopath
  file:
    path: "{{ buildDir }}/go"
    state: directory

- name: create source path
  file:
    path: "{{ buildDir }}/go/src/github.com/katzenpost/daemons"
    state: directory

- name: install godep
  environment:
    GOPATH: "{{ buildDir }}/go"
    PATH: "{{ buildDir }}/go/bin:{{ ansible_env.PATH }}"
  command: go get -u github.com/golang/dep/cmd/dep

- name: clone the daemons repository
  git:
    repo: https://github.com/katzenpost/daemons
    dest: "{{ buildDir }}/go/src/github.com/katzenpost/daemons"
    version: voting_release

- name: run dep ensure
  environment:
    GOPATH: "{{ buildDir }}/go"
    PATH: "{{ buildDir }}/go/bin:{{ ansible_env.PATH }}"
  command: dep ensure
  args:
    chdir: "{{ buildDir }}/go/src/github.com/katzenpost/daemons"

- name: go install nonvoting authority
  environment:
    GOPATH: "{{ buildDir }}/go"
    PATH: "{{ buildDir }}/go/bin:{{ ansible_env.PATH }}"
  command: go install
  args:
    chdir: "{{ buildDir }}/go/src/github.com/katzenpost/daemons/authority/nonvoting"

- name: go install voting authority
  environment:
    GOPATH: "{{ buildDir }}/go"
    PATH: "{{ buildDir }}/go/bin:{{ ansible_env.PATH }}"
  command: go install
  args:
    chdir: "{{ buildDir }}/go/src/github.com/katzenpost/daemons/authority/voting"

- name: go install server
  environment:
    GOPATH: "{{ buildDir }}/go"
    PATH: "{{ buildDir }}/go/bin:{{ ansible_env.PATH }}"
  command: go install
  args:
    chdir: "{{ buildDir }}/go/src/github.com/katzenpost/daemons/server"

- name: ensure latest directory exists
  file:
    path: latest
    state: directory

- name: fetch server binary
  fetch:
    src: "{{ buildDir }}/go/bin/server"
    flat: yes
    dest: latest/server

- name: fetch nonvoting binary
  fetch:
    src: "{{ buildDir }}/go/bin/nonvoting"
    flat: yes
    dest: latest/nonvoting

- name: fetch voting binary
  fetch:
    src: "{{ buildDir }}/go/bin/voting"
    flat: yes
    dest: latest/voting
