---
- name: update the authority identity public key
  copy: src="{{ idPubKey }}" dest=/var/lib/katzenpost-authority/identity.public.pem owner=katzenpost-authority group=katzenpost-authority mode=0600

- name: update the authority identity private key
  copy: src="{{ idPrivKey }}" dest=/var/lib/katzenpost-authority/identity.private.pem owner=katzenpost-authority group=katzenpost-authority mode=0600
  notify:
    - restart katzen-authority
