- name: update the authority identity key
  copy: src=./identity.public.pem dest=/var/lib/katzenpost/identity.public.pem owner=root group=katzenpost mode=0640
  copy: src=./identity.private.pem dest=/var/lib/katzenpost/identity.private.pem owner=root group=katzenpost mode=0640
  notify:
    - restart katzen-authority
